
//! Autogenerated weights for `pallet_evm_deployment_control`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.0.0
//! DATE: 2025-10-14, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `fedora`, CPU: `AMD Ryzen 7 7840U w/ Radeon  780M Graphics`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./target/release/evm-template-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_evm_deployment_control
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// pallets/evm-deployment-control/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions needed for pallet_evm_deployment_control.
pub trait WeightInfo {
	fn authorize_deployer() -> Weight;
	fn revoke_deployer() -> Weight;
	fn is_authorized_check() -> Weight;
}

/// Weights for pallet_evm_deployment_control using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `EvmDeploymentControl::AuthorizedDeployers` (r:1 w:1)
	/// Proof: `EvmDeploymentControl::AuthorizedDeployers` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	fn authorize_deployer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3`
		//  Estimated: `3501`
		// Minimum execution time: 9_498_000 picoseconds.
		Weight::from_parts(10_686_000, 0)
			.saturating_add(Weight::from_parts(0, 3501))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `EvmDeploymentControl::AuthorizedDeployers` (r:1 w:1)
	/// Proof: `EvmDeploymentControl::AuthorizedDeployers` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	fn revoke_deployer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `63`
		//  Estimated: `3501`
		// Minimum execution time: 10_685_000 picoseconds.
		Weight::from_parts(11_873_000, 0)
			.saturating_add(Weight::from_parts(0, 3501))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `EvmDeploymentControl::AuthorizedDeployers` (r:1 w:0)
	/// Proof: `EvmDeploymentControl::AuthorizedDeployers` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	fn is_authorized_check() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `63`
		//  Estimated: `3501`
		// Minimum execution time: 4_749_000 picoseconds.
		Weight::from_parts(5_937_000, 0)
			.saturating_add(Weight::from_parts(0, 3501))
			.saturating_add(T::DbWeight::get().reads(1))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	fn authorize_deployer() -> Weight {
		Weight::from_parts(10_686_000, 3501)
			.saturating_add(Weight::from_parts(0, 3501))
			.saturating_add(frame_support::weights::constants::RocksDbWeight::get().reads(1))
			.saturating_add(frame_support::weights::constants::RocksDbWeight::get().writes(1))
	}
	fn revoke_deployer() -> Weight {
		Weight::from_parts(11_873_000, 3501)
			.saturating_add(Weight::from_parts(0, 3501))
			.saturating_add(frame_support::weights::constants::RocksDbWeight::get().reads(1))
			.saturating_add(frame_support::weights::constants::RocksDbWeight::get().writes(1))
	}
	fn is_authorized_check() -> Weight {
		Weight::from_parts(5_937_000, 3501)
			.saturating_add(Weight::from_parts(0, 3501))
			.saturating_add(frame_support::weights::constants::RocksDbWeight::get().reads(1))
	}
}
